DROP TABLE IF EXISTS banks_users;
DROP TABLE IF EXISTS banks;
DROP TABLE IF EXISTS countries;
DROP TABLE IF EXISTS users;

DROP SEQUENCE IF EXISTS country_id_seq;
DROP SEQUENCE IF EXISTS bank_id_seq;
DROP SEQUENCE IF EXISTS users_id_seq;


CREATE SEQUENCE IF NOT EXISTS country_id_seq START WITH 1;
CREATE SEQUENCE IF NOT EXISTS bank_id_seq START WITH 1;
CREATE SEQUENCE IF NOT EXISTS users_id_seq START WITH 1;

CREATE TABLE countries
(
    id          integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  varchar(100)                             NOT NULL,
    CONSTRAINT pk_country_id PRIMARY KEY (id)
);

CREATE TABLE banks
(
    id        integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name      varchar(100)                             NOT NULL,
    country_id integer                                  NOT NULL,
    CONSTRAINT pk_bank_id PRIMARY KEY (id)
);

CREATE TABLE users
(
    id      integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name    varchar(120)                             NOT NULL,
    email   varchar(220)                             NOT NULL,
    sex varchar(120),
    CONSTRAINT users_pkey PRIMARY KEY (id)
);

CREATE TABLE banks_users
(
    user_id integer NOT NULL,
    bank_id integer NOT NULL,
    CONSTRAINT pk_banks_rating_user_id PRIMARY KEY (user_id, bank_id)
);

ALTER TABLE banks ADD CONSTRAINT fk_bank_country FOREIGN KEY (country_id) REFERENCES countries (id);
ALTER TABLE banks_users ADD CONSTRAINT fk_users_banks_users FOREIGN KEY (user_id) REFERENCES users (id);
ALTER TABLE banks_users ADD CONSTRAINT fk_users_banks_banks FOREIGN KEY (bank_id) REFERENCES banks (id);